spring:
  profiles:
    active: dev

  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect

  datasource:
    url: jdbc:mysql://localhost:3307/test_db
    username: user
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    baseline-on-migrate: true

logging:
  level:
    org:
      hibernate:
        SQL: debug