spring:

  jpa:
    generate-ddl: true
    database: mysql
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  datasource:
    url: jdbc:mysql://localhost/my_app
    username: my_app
    password: se3ret

  flyway:
    baseline-on-migrate: true

logging:
  level:
    org:
      hibernate:
        SQL: debug