CREATE TABLE TAB_CUSTOMER (	ID BIGINT AUTO_INCREMENT PRIMARY KEY);

CREATE TABLE TAB_PROJECTS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	CUSTOMER_ID BIGINT NULL,
	CONSTRAINT FK_CUSTOMER_PT
		FOREIGN KEY (CUSTOMER_ID) REFERENCES TAB_CUSTOMER (ID)
);
